export const TECH_COLORS = {
    Python: 'bg-blue-600 text-white',
    JavaScript: 'bg-yellow-400 text-black',
    TypeScript: 'bg-blue-500 text-white',
    React: 'bg-cyan-500 text-white',
    Vue: 'bg-green-500 text-white',
    Angular: 'bg-red-600 text-white',
    Svelte: 'bg-orange-500 text-white',
    FastAPI: 'bg-teal-600 text-white',
    Flask: 'bg-gray-700 text-white',
    Django: 'bg-green-700 text-white',
    Node: 'bg-green-600 text-white',
    'Node.js': 'bg-green-600 text-white',
    Express: 'bg-gray-600 text-white',
    NestJS: 'bg-red-500 text-white',
    Next: 'bg-black text-white',
    'Next.js': 'bg-black text-white',
    Nuxt: 'bg-green-600 text-white',
    'Nuxt.js': 'bg-green-600 text-white',
    Vite: 'bg-purple-600 text-white',
    Webpack: 'bg-blue-400 text-white',
    Docker: 'bg-blue-500 text-white',
    Kubernetes: 'bg-blue-600 text-white',
    PostgreSQL: 'bg-blue-700 text-white',
    MySQL: 'bg-orange-600 text-white',
    MongoDB: 'bg-green-600 text-white',
    Redis: 'bg-red-600 text-white',
    GraphQL: 'bg-pink-600 text-white',
    REST: 'bg-green-500 text-white',
    Git: 'bg-orange-500 text-black',
    GitHub: 'bg-gray-800 text-white',
    GitLab: 'bg-orange-600 text-white',
    AWS: 'bg-orange-500 text-black',
    Azure: 'bg-blue-600 text-white',
    GCP: 'bg-blue-500 text-white',
    Tailwind: 'bg-cyan-500 text-white',
    'Tailwind CSS': 'bg-cyan-500 text-white',
    Bootstrap: 'bg-purple-600 text-white',
    CSS: 'bg-blue-500 text-white',
    HTML: 'bg-orange-500 text-black',
    SCSS: 'bg-pink-500 text-white',
    Sass: 'bg-pink-500 text-white',
}

export function getTechColor(tech) {
    return TECH_COLORS[tech] || 'bg-bob-primary text-white'
}